APP_PREFIX = 'apps.'

HANDLE_FN_SUFFIX = '_handle'
HANDLE_CLASS_SUFFIX = 'Handler'
HANDLE_FN_DEFAULT = 'default' + HANDLE_FN_SUFFIX
HANDLE_CLASS_DEFAULT = 'Default' + HANDLE_CLASS_SUFFIX

FILE_EXT = '.html'
FAKE_STATIC = False # 伪静态
FAKE_STATIC_EXT = FILE_EXT